version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: rustproject
    environment:
      - POSTGRES_USER=coc
      - POSTGRES_PASSWORD=pwd123
      - POSTGRES_DB=coc
    ports:
      - '54320:5432'