// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use chrono::NaiveDate;

#[derive(Queryable, Debug, Identifiable)]
#[primary_key(committee_id)]
pub struct Committee {
    pub committee_id: i32,
    pub name: String,
    pub description: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
#[primary_key(email, committee_id)]
pub struct CommitteeAssignment {
    pub email: String,
    pub committee_id: i32,
    pub start_date: Option<NaiveDate>,
    pub end_date: Option<NaiveDate>,
}

#[derive(Queryable, Debug, Identifiable)]
#[primary_key(department_id)]
pub struct Department {
    pub department_id: i32,
    pub name: String,
    pub description: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
#[primary_key(email, department_id)]
pub struct DepartmentAssociation {
    pub email: String,
    pub department_id: i32,
}

#[derive(Queryable, Debug, Identifiable)]
#[primary_key(email)]
pub struct Faculty {
    pub faculty_id: i32,
    pub full_name: String,
    pub email: String,
    pub job_title: Option<String>,
    pub senate_division: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[primary_key(choice_id, email, survey_date, committee_id)]
pub struct SurveyChoice {
    pub choice_id: i32,
    pub survey_date: NaiveDate,
    pub email: String,
    pub committee_id: i32,
}

#[derive(Queryable, Debug, Identifiable)]
#[primary_key(survey_date, email)]
pub struct SurveyData {
    pub survey_date: NaiveDate,
    pub email: String,
    pub is_interested: bool,
    pub expertise: Option<String>,
}

